version: '3'

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - "./sonarqube/data:/opt/sonarqube/data"
      - "./sonarqube/extensions:/opt/sonarqube/extensions"